### PR TITLE
#906 Get rid of xembly as a dependency

### PR DESCRIPTION
**Pull request by longtimeago**
@krzyk please, take a look :)

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#907](https://github.com/teamed/qulice/issues/907) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#907](https://github.com/teamed/qulice/issues/907); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#907](https://github.com/teamed/qulice/issues/907); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#907](https://github.com/teamed/qulice/issues/907); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#907](https://github.com/teamed/qulice/issues/907); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by longtimeago** [comment]
@krzyk checked locally - it passes if javac is pointing at jdk8 but fails if > 8.
For the test under consideration we generate classfile running a child process with javac https://github.com/teamed/qulice/blob/2288e88dec3f40daf0a3c386ad253c47cfa14af8/qulice-findbugs/src/mock/java/com/qulice/findbugs/BytecodeMocker.java#L72

Then findbugs tries to read that classfile and fails in `org.objectweb.asm.ClassReader#ClassReader(byte[], int, int)`
on
```java
        // checks the class version
        if (readShort(off + 6) > Opcodes.V1_8) {
            throw new IllegalArgumentException();
        }
```
with 
```java
The following errors occurred during analysis:
  Error scanning Foo for referenced classes
    java.lang.IllegalArgumentException
      At org.objectweb.asm.ClassReader.<init>(Unknown Source)
      At org.objectweb.asm.ClassReader.<init>(Unknown Source)
      At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
      At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:774)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:222)
      At com.qulice.findbugs.Wrap.run(Wrap.java:134)
      At com.qulice.findbugs.Wrap.main(Wrap.java:72)
```

Travis build failed because travis uses `javac` from jdk9 for some reason
https://travis-ci.org/teamed/qulice/jobs/393331163#L464
```java
$ javac -J-Xmx32m -version
javac 9.0.1
```
Even if `java` resolves to a proper version
```java
$ java -Xmx32m -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3~14.04-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
```

**Comment by longtimeago** [comment]
for the reference, previous travis builds worked correctly 
https://travis-ci.org/teamed/qulice/jobs/375863825

```java
$ java -Xmx32m -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3~14.04-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_141
```

So, most probably it's travis's bug

**Comment by longtimeago** [comment]
registered a bug in jdk_switcher https://github.com/michaelklishin/jdk_switcher/issues/19

**Comment by krzyk** [comment]
@longtimeago OK, so let's try it

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#907` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#907](https://github.com/teamed/qulice/issues/907) is now out of scope

**Pull request merged**
