### PR TITLE
#590 removed findbugs exclude

### PR DESCRIPTION
**Pull request by krzyk**
#590 
* removed findbugs exclude (except for one generated class) and updated code

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks, let me find someone who can review this pull request

**Comment by davvd** [comment]
@caarlos0 please review, thanks

**Comment by caarlos0** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor deploy

**Comment by davvd** [comment]
@caarlos0 Many thanks! **16 mins** were added to your account in Transaction ID `569769417cca5509640001a2` (task took 47 hours and 7 mins)... you're getting extra minutes here (c=1)... +16 added to your rating, at the moment it is: [+157](http://www.netbout.com/b/35095?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
