### PR TITLE
#527 Enable strict condition in Checkstyle Indentation check

### PR DESCRIPTION
**Pull request by mkordas**
For #527:
* change config for Indentation check to enforce strict indentation (not more spaces than needed)
* unit test added

### CODE REVIEW

**Comment by davvd** [comment]
@mkordas Thanks, let me find someone who can review this pull request

**Comment by davvd** [comment]
@longtimeago review this one,please

**Comment by longtimeago** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@rultor deploy pls

**Comment by davvd** [comment]
@longtimeago done, I added **16 mins** in payment `72989616`, 23 hours and 4 mins spent to complete this. extra minutes for review comments (c=1). +16 added to your rating, current score is: [+1459](http://www.netbout.com/b/35024?open=rating)

**Pull request merged**
