### PR TITLE
#609 Remove unnecessary usages of 'ConcurrentHashMap'

### PR DESCRIPTION
**Pull request by mkordas**
For #609:
* update Qulice to 0.15.2
* replace usages of `ConcurrentHashMap` with `HashMap`
* remove suppression
* remove puzzle

### CODE REVIEW

**Comment by davvd** [comment]
@mkordas Thanks, let me find someone who can review this pull request

**Comment by davvd** [comment]
@dmzaytsev it's yours,please review

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by mkordas** [comment]
@rultor deploy

**Comment by krzyk** [comment]
@rultor deploy

**Comment by davvd** [comment]
@rultor please deploy

**Comment by davvd** [comment]
@dmzaytsev **16 mins** was added to your account, many thanks for your contribution (payment 74718531)! The task took 2 hours and 9 mins.

review comments (c=1) added as a bonus

+16 to your rating, your total score is [+1971](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
