### PR TITLE
For #917: Make ProtectedMethodInFinalClassCheck stricter.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #917:
- Added condition to failure test: when a default method is overrided by a protected one in a final class checkstyle should complain
- Added puzzle for completion of the task

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#993](https://github.com/teamed/qulice/issues/993); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#993` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#993](https://github.com/teamed/qulice/issues/993) is now out of scope

**Pull request merged**
