### PR TITLE
#380: added documentation to README.md on the necessity of JDK binaries ...

### PR DESCRIPTION
**Pull request by pinaf**
#380 ...(e.g. javac) being accessible from the PATH environment variable.

### CODE REVIEW

**Comment by davvd** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by davvd** [comment]
@longtimeago this pull request is for you, please review

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@longtimeago paid, thanks, added **17 mins** to your account, payment `50593456`. +17 added to your rating, current score is: [+1254](http://www.netbout.com/b/35024?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
