### PR TITLE
For #1006: Making ProtectedMethodInFinalClassCheck stricter.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1006: 
- Making `ProtectedMethodInFinalClassCheck` stricter by adding checks.
- Corrected tests for new check.

### CODE REVIEW

**Comment by krzyk** [comment]
@paulodamaso you forgot to remove the todo :)

**Comment by paulodamaso** [comment]
@krzyk As usual :)

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#1025](https://github.com/teamed/qulice/issues/1025) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#1025](https://github.com/teamed/qulice/issues/1025); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job [#1025](https://github.com/teamed/qulice/issues/1025) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't retrieve data and time of add

**Comment by 0crat** [comment]
This pull request [#1025](https://github.com/teamed/qulice/issues/1025) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3T49A35L/0af06378-44b0-4750-9041-fdada6aa9cbb); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @krzyk[/z](https://www.0crat.com/u/krzyk) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#1025` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1025](https://github.com/teamed/qulice/issues/1025) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by ypshenychka** [comment]
@krzyk According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews

**Comment by ypshenychka** [comment]
@krzyk oh sorry. You're not assigned here. Still the queality will be bad, as reviewer was PR author and didn't perform any review

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/teamed/qulice/issues/1025#issuecomment-461519837))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
