### PR TITLE
#471 tuned check to not report a problem when constructor params equal  fields

### PR DESCRIPTION
**Pull request by krzyk**
#471 
* added test to check the new condition for constructor params (allow same name as fields) and for method params (no change)
* fixed by adding `HiddenField` parameter

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Let me find a reviewer for this pull request, thanks for submitting it

**Comment by davvd** [comment]
@caarlos0 please review, thanks

**Comment by caarlos0** [comment]
@krzyk NICE! thanks!

**Comment by caarlos0** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@rultor please deploy

**Comment by davvd** [comment]
@caarlos0 I just added **17 mins** to your account, many thanks for your contribution (AP-9EJ56672D75252131).. 48 hours and 9 mins spent here... you're getting extra minutes here (c=2)... +17 to your rating, your total score is [+1104](http://www.netbout.com/b/35095?open=rating)

**Pull request merged**
