### PR TITLE
#474 added information about start and finish of validators

### PR DESCRIPTION
**Pull request by krzyk**
#474
* added logging of validator start and end
* added IT test to check the above addition

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@caarlos0 it's yours, please review

**Comment by caarlos0** [comment]
@rultor merge

**Comment by davvd** [comment]
@caarlos0 thanks, I just added **16 mins** to your account, payment `565572232fa56d008d0000e0`, 22 hours spent. review comments (c=1) added as a bonus. +16 added to your rating, at the moment it is: [+768](http://www.netbout.com/b/35095?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
