### PR TITLE
#448 fixed NPE problem in Maven Env

### PR DESCRIPTION
**Pull request by krzyk**
#448
* recreated problem in integration test (using a dependency that has the `<relocation>` in pom)
* `<relocation>` tag was causing NPE (this dependency doesn't have a jar) - fixed by checking if artifact has a file associated

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks, I will find someone to review this PR soon

**Comment by davvd** [comment]
@carlosmiranda review this one,please

**Comment by carlosmiranda** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by krzyk** [comment]
@rultor deploy pls

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor release tag is `0.12.2`

**Comment by davvd** [comment]
@carlosmiranda done, I added **16 mins** in payment `62980440`, 1 hour and 24 mins spent to complete this... review comments (c=1) added as a bonus... +16 added to your rating, current score is: [+3254](http://www.netbout.com/b/35023?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
