### PR TITLE
Page 'qulice.com' is currently broken #578

### PR DESCRIPTION
**Pull request by HDouss**
Resolving #578 
* revoke commit cadf2a75bfc0e9bda2909dfe6685596b7fe831ce changes
* let the apidocs-0.15 folder

### CODE REVIEW

**Comment by krzyk** [comment]
@HDouss page was broken even before this commit, so it is not the cause

**Comment by HDouss** [comment]
@krzyk page was broken in commit 622dc3defcffe5d81e42c2e98c0ddf78b5222048, then fixed in commit 589f3692af6de8ad045ab930467a74e44bc51831, and then broken again in commit cadf2a75bfc0e9bda2909dfe6685596b7fe831ce.

**Comment by krzyk** [comment]
@HDouss but those pages are AFAIK generated using `mvn site`

**Comment by HDouss** [comment]
@krzyk I am not sure I understand your comment. Could you please explain ? Do you mean that even pages like root `index.html` are generated ?

**Comment by krzyk** [comment]
@HDouss please see rultor configuration in the project, it contains:
```
    mvn clean site-deploy -Pgh-pages -Pqulice-profile -Psite --errors --settings ../settings.xml || echo 'site-deploy failed'
```

**Comment by HDouss** [comment]
@krzyk That does not mean that site generation does not take and include static pages to generate the site. I don't understand the problem with this PR.

**Comment by krzyk** [comment]
@HDouss I just think this site is generated automatically
@yegor256 are all gh-pages generated automatically using `mvn site-deploy` or is there a manual step?

**Comment by HDouss** [comment]
@krzyk The manual step is to provide content inside *.html pages, which explains the commits.

**Comment by krzyk** [comment]
@HDouss do you have example of content that is in those pages and is not in html pages generated by `mvn clean site -Pgh-pages -Pqulice-profile -Psite`?

**Comment by HDouss** [comment]
@krzyk I am not sure I understand you well. What I said is that generation comes from those static pages. So modifying those static pages is enough to modify site content.
Do you mean that static html files commited on gh-pages branch comes from result of `mvn clean site -Pgh-pages -Pqulice-profile -Psite` ?

**Comment by krzyk** [comment]
@HDouss yes, if you look at dates of https://github.com/teamed/qulice/releases and dates of https://github.com/teamed/qulice/commits/gh-pages you will see they are very close to each other (minutes close)

**Comment by HDouss** [comment]
@krzyk The commits are always preceding the releases. I think gh-pages branch is the source of the generation, not the output of it. How do you explain that last commit on master branch src/site is 6 months old ?

**Comment by krzyk** [comment]
@HDouss no, I made changes to the qulice.com, without even knowing that there are gh-pages months/years ago. If you look at the generated site you will see that the page looks exactly the same (except the fact that the one in gh-pages is broken). Maybe the upload function to gh-pages somehow broke? It is defined in jcabi-parent project pom.xml, and the look&feel is in jcabi-maven-skin.
What I see in gh-pages looks like that all modules are uploaded into the same place - this would explain multiple commits, each one might be for seperate module, but all upload to the same path and this breaks the qulice.com.

**Comment by HDouss** [comment]
@krzyk I understand better. Thanks for your time. What confused me (and may be the source of the problem) is that commits on gh-pages branch are always authored yegor@teamed.io until Dec 23. Starting Dec 31, the commits are authored by yegor@tpc2.com. I wonder if it is always automated uploads or some commits were manual.

**Comment by caarlos0** [comment]
@HDouss `gh-pages` branch is used by github pages. You can see more on it here: https://pages.github.com/

If create a gh-pages branch in any repo and put a simple index.html inside it, it automatically becomes a site under github.io domain (user.github.io/project-name)...

That being said, I believe that all those commits were made by rultor using yegor's key...

**Comment by davvd** [comment]
@hdouss Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@dmzaytsev review this one, please

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by yegor256** [comment]
@krzyk everything is done automatically, no manual steps there

**Comment by krzyk** [comment]
@HDouss please close this PR, as the problem is somewhere else

**Comment by dmzaytsev** [comment]
@krzyk @HDouss do we know exactly when the site became broken?

**Comment by HDouss** [comment]
@dmzaytsev Not exactly, but it was noticed on Jan 1st. I think it is somehow related to Dec 31 automated commits (or uploads).

**Comment by dmzaytsev** [comment]
@HDouss did you try to exec  'mvn clean install site' and to open local file `target/site/index.html` in your browser ? does the site look correct?

**Comment by HDouss** [comment]
@dmzaytsev Yes it looks correct. I think something is broken elsewhere. Most probably not in qulice project.

**Comment by dmzaytsev** [comment]
@krzyk maybe a new release will help ?

**Comment by krzyk** [comment]
@dmzaytsev I don't think so, I just did today

**Comment by HDouss** [comment]
@krzyk Please see and/or continue discussion on #605

**Comment by davvd** [comment]
> @davvd this is postponed 

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed 

@krzyk right, I'll try to find someone else for this task

**Comment by HDouss** [comment]
@davvd I am working on the issue, and I am resolving it. I have PR #605 that is waiting for review. Why trying to find someone else ?

**Comment by krzyk** [comment]
@HDouss this is the previous PR, you can close it

**Comment by HDouss** [comment]
@krzyk Ok. It is already closed.

**Pull request closed without merging**
