### PR TITLE
#1031. Now UseStringIsEmptyRule not detect String[].length > 0.

### PR DESCRIPTION
**Pull request by zCRUSADERz**
For #1031 

- Add test case where used String[].length.
- Fix UseStringIsEmptyRule, now it does not detect this case.

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#1043](https://github.com/teamed/qulice/issues/1043) is now in scope, role is `REV`

**Comment by zCRUSADERz** [comment]
@krzyk i apologize, in this pull request there are commits from another branch, to which a pull request has already been created #1040. These changes are interrelated and I have not found a better way to do it correctly.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#1043](https://github.com/teamed/qulice/issues/1043); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#1043` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1043](https://github.com/teamed/qulice/issues/1043) is now out of scope

**Comment by 0crat** [comment]
Pull request [#1043](https://github.com/teamed/qulice/issues/1043) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
