### PR TITLE
For #738: Qulaify inner classes

### PR DESCRIPTION
**Pull request by paulodamaso**
For #738: Qulaify inner classes
- Addes test to ensure that inner classes are being accessed through qualified name
- Left puzzle for check implementatio

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#987](https://github.com/teamed/qulice/issues/987) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#987](https://github.com/teamed/qulice/issues/987); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@krzyk ping

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#987](https://github.com/teamed/qulice/issues/987); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@paulodamaso one comment, and make sure to update the copyright years

**Comment by paulodamaso** [comment]
@krzyk Which comment?

**Comment by krzyk** [comment]
@paulodamaso now it is visible :)

**Comment by paulodamaso** [comment]
@krzyk Thanks done the correction please take a look

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#987` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#987](https://github.com/teamed/qulice/issues/987) is now out of scope

**Pull request merged**
