### PR TITLE
#355 Add handling of anonymous classes...

### PR DESCRIPTION
**Pull request by maxim-kornienko**
Everything seems to be ok already. See discusion in ticket.

### CODE REVIEW

**Comment by davvd** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@krzyk please review, thanks

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@krzyk done, I added **17 mins** in payment `50344420`... +17 added to your rating, current score is: [+2013](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
