### PR TITLE
#421 Add test for multiline exclusion for FindBugs

### PR DESCRIPTION
**Pull request by mkordas**
For #421:
* Add two separate exclusions instead of one in integration test (we have two files with violations already, test is failing when leaving just one of them)
* Remove puzzle from the code
* Adjust documentation

### CODE REVIEW

**Comment by davvd** [comment]
@mkordas I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@krzyk pull request is rather short, review it please

**Comment by krzyk** [comment]
@mkordas looks good, thanks

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@krzyk Thanks so much! Your account was topped up for **17 mins** (transaction ID is `73937650`, the task took 2 hours and 13 mins). review comments (c=2) added as a bonus. +17 to your rating, your total score is [+2960](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
