### PR TITLE
#611 Static constants are not checked to have class specified

### PR DESCRIPTION
**Pull request by HDouss**
Resolving #611 by PMD XPath rule.
Added A positive and a negative unit test.

### CODE REVIEW

**Comment by HDouss** [comment]
@davvd PR ready for review. Please assign a reviewer.

**Comment by davvd** [comment]
@hdouss Thanks for your pull request, let me find someone who can review it

**Comment by HDouss** [comment]
@davvd PR ready. Please assign a reviewer.

**Comment by krzyk** [comment]
@HDouss have you tried rejoinging the qulice team?

**Comment by HDouss** [comment]
@krzyk Yes just now. Yesterday it was approval than rejection. Is it so important ? (takes does not work that way)

**Comment by krzyk** [comment]
@HDouss Unfortunatelly I don't know why it happens, and if it is important, @yegor256 asked if you are so I assume it should be.
Maybe that's the reason we get sometimes postponed flag added in your tickets.

**Comment by HDouss** [comment]
@krzyk OK.

**Comment by davvd** [comment]
> @davvd PR ready for review. Please assign a reviewer.

@hdouss OK, sure

**Comment by davvd** [comment]
> @davvd PR ready. Please assign a reviewer.

@hdouss OK, sure

**Comment by davvd** [comment]
@caarlos0 review this one, please

**Comment by caarlos0** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@rultor deploy

**Comment by davvd** [comment]
@caarlos0 since quality is good, 10 mins paid to @krzyk (our architect), transaction `76556804`

**Comment by caarlos0** [comment]
@davvd I didn't get paid for this one...

**Comment by caarlos0** [comment]
@yegor256 didn't get paid here

**Comment by caarlos0** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@davvd pls add extra 15 mins to @caarlos0  here

**Comment by caarlos0** [comment]
@yegor256 I didn't get paid for this one

**Pull request merged**
