### PR TITLE
#950 fix rultor

### PR DESCRIPTION
**Pull request by krzyk**
#950 
* fix for deprecated gem options

### CODE REVIEW

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @krzyk[/z](https://www.0crat.com/u/krzyk) please review this and merge or reject

**Comment by krzyk** [comment]
@yegor256 could you merge this change directly to master? gem removed the `--no-ri` and `--no-rdoc` options and apperantly we should use `--no-document` now, but I don't have permissions to do it directly on master.

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by korthout** [comment]
This is already blocking 6 pull requests. @yegor256 Please take a look at it.

**Comment by yegor256** [comment]
@krzyk done

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#979` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
