### PR TITLE
#552 Dependencies to google-collections and guava-io should be removed

### PR DESCRIPTION
**Pull request by HDouss**
Resolving #552
* Unnecessary dependencies removed
* Upgrade guava version to 19.0 by inheritance (guava version no longer hardcoded)

### CODE REVIEW

**Comment by davvd** [comment]
@hdouss Many thanks for the PR, let me find a reviewer for it

**Comment by davvd** [comment]
@carlosmiranda review this one, please

**Comment by carlosmiranda** [comment]
@HDouss looks good, thanks!

**Comment by carlosmiranda** [comment]
@rultor merge please

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@carlosmiranda I just added **17 mins** to your account, many thanks for your contribution (73592391).. 21 hours and 2 mins spent here

extra minutes for review comments (c=2)

+17 added to your rating, at the moment it is: [+2510](http://www.netbout.com/b/35023?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
