### PR TITLE
#388 removed stale todo

### PR DESCRIPTION
**Pull request by krzyk**
#388 
* removed stale todo, it was fixed in #131

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks, I will find someone to review this PR soon

**Comment by davvd** [comment]
@krzyk this pull request is too short and it's from the architect, no need to do any code review here, just merge it

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@rultor deploy

**Pull request merged**
