### PR TITLE
#370 removed findbugs exludes

### PR DESCRIPTION
**Pull request by krzyk**
#370 
* removed findbugs (and fixed problems) exclude in qulice-ant, qulice-gradle-plugin, qulice-findbugs
* added todo to remove the exclude in qulice-maven-plugin

### CODE REVIEW

**Comment by krzyk** [comment]
@davvd please find reviewer

**Comment by davvd** [comment]
@krzyk Thanks, I will find someone to review this PR soon

**Comment by davvd** [comment]
@dmzaytsev review this one,please

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor deploy pls

**Comment by davvd** [comment]
@rultor deploy pls

**Comment by davvd** [comment]
@dmzaytsev **16 mins** added to your account (payment number `73948649`), many thanks for your contribution! 23 hours and 10 mins spent here.... you're getting extra minutes here (c=1)... +16 added to your rating, current score is: [+1334](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
