### PR TITLE
NonStaticMethodCheck is commented out in checks.xml #542

### PR DESCRIPTION
**Pull request by HDouss**
Resolving #542.
-Check reenabled
-Unit tests already exist for NonStaticMethodCheck
-Fix the unit test that would fail due to reenabling NonStaticMethodCheck

### CODE REVIEW

**Comment by davvd** [comment]
@hdouss Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@dmzaytsev review this one, please

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@dmzaytsev Thanks for your contribution, **16 mins** was added to your account, payment ID is `73861296`, 93 hours and 35 mins spent total... you're getting extra minutes here (c=1)... +16 added to your rating, at the moment it is: [+1185](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
