### PR TITLE
#848 dont require javadoc for methods in tests

### PR DESCRIPTION
**Pull request by krzyk**
#848
* removed requirement for method javadocs in test classes

### CODE REVIEW

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#947](https://github.com/teamed/qulice/issues/947) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#947](https://github.com/teamed/qulice/issues/947) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3T49A35L/2bc93d06-1a19-493e-9924-6d784cde3c99); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @krzyk[/z](https://www.0crat.com/u/krzyk) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by krzyk** [comment]
@rultor stop

**Comment by krzyk** [comment]
@rultor merge

**Comment by krzyk** [comment]
@paulodamaso sorry I didn't know you are in the project

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#947](https://github.com/teamed/qulice/issues/947) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by ypshenychka** [comment]
@paulodamaso According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by paulodamaso** [comment]
@paulodamaso I confirm, I didn't even touched this one

**Comment by ypshenychka** [comment]
@paulodamaso thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
