### PR TITLE
#400 added explanation for license

### PR DESCRIPTION
**Pull request by krzyk**
#400
* added more explicit information about license file location

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@yegor256 Thanks a lot, I just topped your account for **16 mins**, transaction ID `000-a564f91f`, total time was 2 hours and 14 mins

review comments (c=1) added as a bonus

+16 added to your rating, current score is: [+13517](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
