### PR TITLE
#741 updated Violations

### PR DESCRIPTION
**Pull request by krzyk**
#741 
* added lines, check name and validator name to the Violations class
* fixed tests

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@longtimeago review this one, please

**Comment by longtimeago** [comment]
@krzyk :+1:

**Comment by longtimeago** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@rultor deploy

**Comment by davvd** [comment]
@longtimeago since quality is good, I just added 10 mins to @krzyk (our architect) in transaction 80479526. **16 mins** added to your account (payment number `80479548`), many thanks for your contribution! 1 hour and 39 mins spent here.. extra minutes for review comments (c=1). +16 added to your rating, at the moment it is: [+7433](http://www.netbout.com/b/35024?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
