### PR TITLE
#61 start of logging unification

### PR DESCRIPTION
**Pull request by krzyk**
#61 
* migrated CheckstyleValidator to new logging (returning violations instead of throwing exception)
* fixed tests
* added todos to migrate rest of the file based validators

### CODE REVIEW

**Comment by krzyk** [comment]
@davvd please find a reviewer

**Comment by davvd** [comment]
@krzyk Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by davvd** [comment]
@pinaf review this one, please

**Comment by pinaf** [comment]
@davvd please assign someone else - no time.

**Comment by davvd** [comment]
> @davvd please find a reviewer

@krzyk OK, got it

**Comment by davvd** [comment]
> @davvd please assign someone else - no time.

@pinaf 15 points was deducted from your rating

**Comment by davvd** [comment]
> @davvd please assign someone else - no time.

@pinaf right, I'll try to find someone else for this task

**Comment by davvd** [comment]
@dmzaytsev please review, thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@rultor deploy pls

**Comment by davvd** [comment]
@dmzaytsev quality is good here, 10 mins added to @krzyk (our architect) in transaction 79287940; Thank you, I have added **16 mins** to your account in payment/transaction "`79287970`", time consumed: 22 hours and 8 mins; extra minutes for review comments (c=1); +16 added to your rating, current score is: [+3829](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Comment by mkordas** [comment]
@krzyk can we quickly revert this PR and release new version? The performance is too bad now.

**Comment by krzyk** [comment]
@mkordas it would be better to fix it instead of reverting, the easiest solution is to revert qulice version in a project to older one

**Pull request merged**
