### PR TITLE
#371 Prohibit multi-line comments in MethodBodyComments check

### PR DESCRIPTION
**Pull request by mkordas**
For #371:
* add one condition to implementation
* extend tests with various cases

### CODE REVIEW

**Comment by davvd** [comment]
@mkordas Thanks, someone will review your pull request soon

**Comment by mkordas** [comment]
@krzyk can you mark it as not postponed?

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by mkordas** [comment]
@davvd please assign reviewer

**Comment by krzyk** [comment]
@davvd assign @dmzaytsev

**Comment by krzyk** [comment]
@dmzaytsev I hope you don't mind :)

**Comment by dmzaytsev** [comment]
@krzyk np :)

**Comment by dmzaytsev** [comment]
@mkordas please add test cases for multi-line comment placed on two or more lines

**Comment by dmzaytsev** [comment]
@mkordas also add something like this  
```
void submit() {
new Runnable() {
            @Override
            public void run() {
                /* run                 
                 */
            }
        };   
}
```

**Comment by mkordas** [comment]
@dmzaytsev done, please see 687c040

**Comment by dmzaytsev** [comment]
@mkordas thanks

**Comment by dmzaytsev** [comment]
@krzyk @mkordas let's wait until I @davvd assign me

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk thanks, I removed the "postponed" tag

**Comment by davvd** [comment]
> @davvd please assign reviewer

@mkordas OK, got it

**Comment by davvd** [comment]
> @davvd assign @dmzaytsev 

@krzyk yep, done. @dmzaytsev it is your task now

**Comment by mkordas** [comment]
@dmzaytsev you are assigned now, can you proceed with merge?

**Comment by dmzaytsev** [comment]
@mkordas sure

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by mkordas** [comment]
@rultor deploy

**Comment by krzyk** [comment]
@rultor deploy

**Comment by davvd** [comment]
@dmzaytsev done, I added **22 mins** in payment `75045442`, 3 hours and 59 mins spent to complete this. you're getting extra minutes here (c=7). +22 to your rating, your total score is [+2128](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
