### PR TITLE
#495 Validate all author tags in JavadocTags check

### PR DESCRIPTION
**Pull request by mkordas**
For #495:
 * Instead of validating only first Javadoc tag, all of them are gathered to the `List` and then validated
 * Test is added to confirm the behaviour

### CODE REVIEW

**Comment by mkordas** [comment]
@davvd please assign reviewer

**Comment by mkordas** [comment]
@krzyk I've opened this PR 2 days ago and it still doesn't have reviewer, please take a look

**Comment by krzyk** [comment]
@mkordas you have to nag @davvd until he does something with it

**Comment by mkordas** [comment]
@davvd please assign reviewer here

**Comment by davvd** [comment]
@mkordas Many thanks for the PR, let me find a reviewer for it

**Comment by davvd** [comment]
@dmzaytsev it's yours,please review

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@mkordas just to make sure I would also add a testcase with two valid authors

**Comment by mkordas** [comment]
@krzyk you are right, added

**Comment by krzyk** [comment]
@mkordas I meant two valid authors in `Valid.java` :)

**Comment by mkordas** [comment]
@krzyk sorry, I haven't read your message carefully enough, please see the new commit

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@rultor deploy

**Comment by davvd** [comment]
@dmzaytsev thank you, added **16 mins** to your acc, payment num is `73948644`, 25 hours and 47 mins spent in total to complete. review comments (c=1) added as a bonus. +16 to your rating, your total score is [+1318](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
