### PR TITLE
ArrayIndexOutOfBoundsException in ImportCohesionCheck on file with imports only #451

### PR DESCRIPTION
**Pull request by HDouss**
Resolving #451

### CODE REVIEW

**Comment by davvd** [comment]
@hdouss Thanks for the pull request, let me find a reviewer..

**Comment by davvd** [comment]
@krzyk review this pls (it's a rather short pull request)

**Comment by krzyk** [comment]
@HDouss you should add a test for this (with the example from the original issue)

**Comment by HDouss** [comment]
@krzyk the example would fail for another reason (NewlineAtEndOfFileCheck). If I add a new line at the end, it would pass the check even without my fix. The only way to do it is to add a unit test inside ChecksTest folder. But here I would add another folder ("ImportCohesionCheck2" ?) without a violation case (or with a dummy one).

**Comment by krzyk** [comment]
@HDouss could you add test to CheckstyleValidatorTest?

**Comment by HDouss** [comment]
@krzyk You mean as an invalid test case where checkstyle should complain about NewlineAtEndOfFileCheck ?

**Comment by krzyk** [comment]
@HDouss yes

**Comment by HDouss** [comment]
@krzyk I am blocked. if I include such a file in the project, we will have our ArrayidexOutOfBounds Exception in the verify phase (that uses qulice 0.15.2). This happens because the exclusion (`<exclude>` tag in pom.xml) happens after the check.

**Comment by krzyk** [comment]
@HDouss you could create the file on the fly, just like in `CheckstyleValidatorTest.catchesCheckstyleViolationsInLicense()` method.

**Comment by HDouss** [comment]
@krzyk Yes. Exactly what I did.

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@krzyk I just added **20 mins** to your account, many thanks for your contribution (75190084).. 26 hours and 8 mins spent here. review comments (c=5) added as a bonus. +20 to your rating, your total score is [+4008](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
