### PR TITLE
for javadoc in Chinese Support

### PR DESCRIPTION
**Pull request by 54uso**

### CODE REVIEW

**Comment by davvd** [comment]
@54uso Let me find a reviewer for this pull request, thanks for submitting it

**Comment by krzyk** [comment]
@54uso I think it would be better to close this PR and submit another one that is more up to date. If you'll do that I'll do a review quickly

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#814` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
