### PR TITLE
Require '@since' tag in class Javadocs #550

### PR DESCRIPTION
**Pull request by HDouss**
Resolving #550 .
* Implementation (expected format : `^\\d+(\\.\\d+)+[a-z]?$` )
* Valid and invalid test cases
* Modification of other unit tests and integration tests to comply with the rule

### CODE REVIEW

**Comment by HDouss** [comment]
@davvd PR ready for review.

**Comment by davvd** [comment]
@hdouss Thanks, someone will review your pull request soon

**Comment by HDouss** [comment]
@davvd Please assign a reviewer.

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd Please assign a reviewer.

@hdouss OK, sure

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk got it, "urgent" label here

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk sure, thanks, I removed "postponed" tags to it

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk sure, thanks, I removed "postponed" tag to it

**Comment by HDouss** [comment]
@davvd Could you please assign a reviewer ?

**Comment by davvd** [comment]
> @davvd Could you please assign a reviewer ?

@hdouss will do when time comes

**Comment by HDouss** [comment]
@krzyk Is it postponed or urgent ?

**Comment by krzyk** [comment]
@yegor256 could you help us here? postponed flag is constantly being added here.

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @pinaf please

**Comment by davvd** [comment]
> @davvd this is not postponed 

@krzyk sure, thanks, I removed "postponed" tag to it

**Comment by davvd** [comment]
> @davvd assign @pinaf please

@krzyk done. @pinaf the task is yours, please go ahead

**Comment by pinaf** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@HDouss build fails, try to merge master and check on your machine

**Comment by HDouss** [comment]
@krzyk Done !

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@pinaf Much appreciated! **16 mins** was added to your account, payment ID `AP-7EC57389W3401890S`, time spent is 117 hours and 15 mins

review comments (c=1) added as a bonus

+16 to your rating, your total score is [+5803](http://www.netbout.com/b/35128?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
