### PR TITLE
For #743: Nested classes should have since tag

### PR DESCRIPTION
**Pull request by paulodamaso**
For #743: Nested classes should have since tag
- Changed `JavadocTagsCheck` tests so it does not pass when `since` tag is absent in nested class
- Removed `JavadocTagsCheck` test execution; the test fails now
- Added puzzle for `JavadocTagsCheck` correction and re-activation of tests

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#988](https://github.com/teamed/qulice/issues/988) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#988](https://github.com/teamed/qulice/issues/988); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@krzyk ping

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#988](https://github.com/teamed/qulice/issues/988); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@krzyk Corrected the puzzle and merged master, please take a look

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#988` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#988](https://github.com/teamed/qulice/issues/988) is now out of scope

**Pull request merged**
