### PR TITLE
For #921: Proof that ConstantUsageCheck false positive does not happen

### PR DESCRIPTION
**Pull request by paulodamaso**
For #921: 
Looks like the problem does not happens anymore, made a test to prove this

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @krzyk[/z](https://www.0crat.com/u/krzyk) please review this and merge or reject

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#995` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
