### PR TITLE
For #1016, #999. UseStringIsEmptyRule

### PR DESCRIPTION
**Pull request by zCRUSADERz**
For #999. 

- Now rule works with `this.somestring.length()` and `this.someMethod().length()`.

For #1016.

- Add test cases for inversed expressions.
- Replace all tests on one parameterized test.

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#1040](https://github.com/teamed/qulice/issues/1040) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#1040](https://github.com/teamed/qulice/issues/1040); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@zCRUSADERz thanks, for future please try to have a single PR per issue

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#1040` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1040](https://github.com/teamed/qulice/issues/1040) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Pull request merged**
