### PR TITLE
For #1000: Added String.length comparison check tests

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1000: 
- Added tests for checking if we are using the length of a string variable to see if it is empty for the missing operators
- Renamed and put all tests and sample files fore this case
- Left puzzle to continue refactor and implementation to strings obtained from a method call and using `this`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1011](https://github.com/teamed/qulice/issues/1011) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#1011](https://github.com/teamed/qulice/issues/1011); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#1011` is not assigned, can't get performer

**Pull request merged**
