### PR TITLE
#666 Disable static method check for ITs and small fixes

### PR DESCRIPTION
**Pull request by mkordas**
For #666:
* Extend pattern for `NonStaticMethodCheck`
* Add tests
* Remove suppressions
* Remove obsolete branch in bash

### CODE REVIEW

**Comment by davvd** [comment]
@mkordas I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@dmzaytsev this pull request is for you, please review

**Comment by dmzaytsev** [comment]
@mkordas keep in mind you not assigned to the ticket yet

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by mkordas** [comment]
@dmzaytsev I know, I wanted to have reviewer before assignment as sometimes @davvd needs 4 days to find CR for PR

**Comment by mkordas** [comment]
@krzyk please confirm merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by mkordas** [comment]
@rultor deploy

**Comment by krzyk** [comment]
@rultor deploy

**Comment by davvd** [comment]
@dmzaytsev quality is good here, 10 mins added to @krzyk (our architect) in transaction 77096884

**Comment by davvd** [comment]
@rultor please deploy

**Comment by davvd** [comment]
@dmzaytsev Much obliged! I have added **17 mins** to your account in payment "77111134", 119 hours and 54 mins spent. you're getting extra minutes here (c=2). +17 added to your rating, current score is: [+3090](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
