### PR TITLE
For #887: Ignore lambdas on constructors.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #887: Ignore lambdas on constructors.
- Created test assuring that `PMD` is ignoring lambda in constructors

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#983](https://github.com/teamed/qulice/issues/983) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#983](https://github.com/teamed/qulice/issues/983); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@paulodamaso thanks

**Comment by krzyk** [comment]
@rultor merge

**Comment by krzyk** [comment]
@0crat waiting for fix in #979

**Comment by 0crat** [comment]
> @0crat waiting for fix in #979  ([here](https://github.com/teamed/qulice/issues/983#issuecomment-454714467))

@krzyk It's a code review job [#983](https://github.com/teamed/qulice/issues/983), can't put it on hold

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#983](https://github.com/teamed/qulice/issues/983); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by llorllale** [comment]
@paulodamaso does this also fix cases where we are using anonymous classes instead of lambdas?

**Comment by paulodamaso** [comment]
@llorllale Actually this PR is just the test, it has no fixes in it; but, anyways, it just tests about lambdas in constructors, doesn't fixing anonymous classes use

**Comment by krzyk** [comment]
@rultor merge

**Comment by krzyk** [comment]
@paulodamaso we need to wait for #997 now

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#983](https://github.com/teamed/qulice/issues/983) is now out of scope

**Pull request merged**
