### PR TITLE
#889 dummy pdd

### PR DESCRIPTION
**Pull request by krzyk**
#889 dummy pdd to test if 0pdd works

### CODE REVIEW

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review; in the future, try to make sure your pull requests are not too small; @krzyk[/z](https://www.0crat.com/u/krzyk) please review this and merge or reject

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request merged**
