### PR TITLE
#469 fixed xml formatting problems

### PR DESCRIPTION
**Pull request by krzyk**
#469 
* fixed problem with XML preambule (now it is required, including encoding)
* fixed problem with comment before the first XML tag
* fixed problem with new line at the and of XML (it is required now)
* added todo to fix incorrect attribute formatting

### CODE REVIEW

**Comment by caarlos0** [comment]
@krzyk Looks good!

**Comment by davvd** [comment]
@krzyk Let me find a reviewer for this pull request, thanks for submitting it

**Comment by davvd** [comment]
@yegor256 this pull request is for you, please review

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@yegor256 Much obliged! I have added **16 mins** to your account in payment "000-e207982c", 24 hours and 12 mins spent. review comments (c=1) added as a bonus. +16 added to your rating, at the moment it is: [+10751](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Comment by caarlos0** [comment]
@davvd can we release this change?

**Comment by davvd** [comment]
> @davvd can we release this change?

@caarlos0 ask @krzyk, he is the architect

**Comment by krzyk** [comment]
@rultor release tag is `0.13.1`

**Comment by krzyk** [comment]
@caarlos0 done, you can use 0.13.1 now

**Comment by caarlos0** [comment]
@krzyk thanks!

**Pull request merged**
