### PR TITLE
#880 upgrade checkstyle, pmd, (and qulice to java 1.8)

### PR DESCRIPTION
**Pull request by krzyk**
#880 
* upgrade checkstyle and PMD
* qulice uses java 1.8 now

### CODE REVIEW

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#924](https://github.com/teamed/qulice/issues/924) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#924](https://github.com/teamed/qulice/issues/924); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#924` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#924](https://github.com/teamed/qulice/issues/924) is now out of scope

**Pull request merged**
