### PR TITLE
#578 fix Page 'qulice.com' is currently broken

### PR DESCRIPTION
**Pull request by HDouss**
Resolving #578. Replace configuration in submodules only.
Pages for qulice should stay at root.

### CODE REVIEW

**Comment by davvd** [comment]
@hdouss Thanks, let me find someone who can review this pull request

**Comment by mkordas** [comment]
@HDouss PR is not mergeable, please check

**Comment by davvd** [comment]
@dmzaytsev please review, thanks

**Comment by dmzaytsev** [comment]
@HDouss please merge with master

**Comment by HDouss** [comment]
@mkordas Thanks !

**Comment by HDouss** [comment]
@dmzaytsev Done.

**Comment by dmzaytsev** [comment]
@HDouss thank you

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge

**Comment by davvd** [comment]
@dmzaytsev Thanks so much! Your account was topped up for **18 mins** (transaction ID is `75231589`, the task took 23 hours and 54 mins)... review comments (c=3) added as a bonus... +18 to your rating, your total score is [+2357](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
