### PR TITLE
#578 Page 'qulice.com' is currently broken

### PR DESCRIPTION
**Pull request by HDouss**
Resolving #578. Generalize github `site-maven-plugin` configuration by putting it on the qulice pom.xml, instead of children project pom.xml.

### CODE REVIEW

**Comment by krzyk** [comment]
@HDouss have you tried if it works correctly?

**Comment by HDouss** [comment]
@krzyk No. How can I do it ? Shouldn't we trigger a release ?

**Comment by krzyk** [comment]
@HDouss well, yes, but triggering a release to debug a problem seams like a overhead, we could end up with 0.15.150 :)
Are you convinced that this will work? I for example saw that 0.12.1 release had a good page (see http://web.archive.org/) so I would compare what changed between 0.12.1 and 0.14, maybe the jcabi-parent changed configuration of the github site plugin somehow, maybe version was upgraded there.

I saw in history that github site plugin was in the submodules for 2-3 years, and it was working then, so why removing it and moving to the top module would fix it?

**Comment by davvd** [comment]
@hdouss Thanks, I will find someone to review this PR soon

**Comment by krzyk** [comment]
@HDouss of course, if you are positive, that this will fix the problem I can trigger a release

**Comment by HDouss** [comment]
@krzyk I think it will resolve the problem because sub modules that has this configuration are uploaded in the right folders. The other modules (that does not have this configuration) are uploaded on the root folder. I topped configuration to the parent module, so every sub module will inherit this configuration. I am positive about one of the two solutions : 
* this one
* make this configuration for every sub module instead of one in the parent (in case configuration inheritance is broken somehow)

**Comment by krzyk** [comment]
@HDouss but why wasn't it working previously? each submodule had a path `${project.artifactId}` which is the name of the module, so nothing should be overwritten

**Comment by HDouss** [comment]
@krzyk I think the right question is : Why it was working previously ? because the configuration of site-maven-plugin in jcabi parent does not fit with our needs `<path>${site.path}</path>`

**Comment by krzyk** [comment]
@HDouss has this configuration changed in parent?

**Comment by HDouss** [comment]
@krzyk I'am afraid I don't have a rigorous explanation. But I think that the bad result we have now is logical, that's why I said: 
>I think the right question is : Why it was working previously ?

it must have something with the fact that we updated from jcabi-parent 0.33 (site-maven-plugin 0.10) to jcabi-parent 0.40 (site-maven-plugin 0.12).

**Comment by krzyk** [comment]
@HDouss OK, so let's try to enforce site-maven-plugin 0.10 only and we'll see what happens

**Comment by HDouss** [comment]
@krzyk I think it is better to give a try on 0.12 with this PR. As I said, it seems weird that it worked properly until now. Let's make a release (or two at maximum) to test.

**Comment by krzyk** [comment]
@HDouss OK, but first PR has to be merged (so we need to wait for reviewer)

**Comment by HDouss** [comment]
@krzyk Let's wait for a reviewer. We have to wait anyway, even if we want to go back to site-maven-plugin 0.10

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd please assign @mkordas

**Comment by mkordas** [comment]
@HDouss please check plugin's history: https://github.com/github/maven-plugins/commits/master/github-site-plugin. No relevant changes between 0.10 and 0.12... So probably there's another root cause.
Moreover, currectly www.qulice.com looks fine. Is it some non-deterministic issue?

**Comment by HDouss** [comment]
@mkordas Currently, the site looks fine because the rultor release [did not finish well](http://www.rultor.com/t/6325-171210006).
>[INFO] qulice ............................................ SUCCESS [07:43 min]
[INFO] qulice-spi ........................................ FAILURE [02:27 min]
[INFO] qulice-checkstyle ................................. SKIPPED
[INFO] qulice-pmd ........................................ SKIPPED
[INFO] qulice-codenarc ................................... SKIPPED
[INFO] qulice-findbugs ................................... SKIPPED
[INFO] qulice-xml ........................................ SKIPPED
[INFO] qulice-ant ........................................ SKIPPED
[INFO] qulice-maven-plugin ............................... SKIPPED
[INFO] qulice-gradle-plugin .............................. SKIPPED

If it has finished well, the qulice-gradle-plugin pages (last one) would have replaced the good ones.

**Comment by HDouss** [comment]
@mkordas @krzyk I think we found it ! Every time rultor release have issues ([here](http://www.rultor.com/t/6325-171210006) and [here](http://www.rultor.com/t/6048-166869769)), the site looks good because 'badly configured' sub modules does not have the chance to overwrite good files. But if the release goes well, the site looks bad. So, I think that changes in this PR will resolve the issue.

**Comment by krzyk** [comment]
@HDouss nice find, it looks like this github deploy fails ofthen because there is an ignore of the build exit code

**Comment by mkordas** [comment]
@krzyk 
>there is an ignore of the build exit code

Where is this ignore? Do you know how this can be fixed?

**Comment by HDouss** [comment]
@mkordas Let's discuss it in another issue. @krzyk whould tell us if it is an issue to be fixed or an intended behaviour (should the site deploy fail block the release or not).
>Where is this ignore? Do you know how this can be fixed?

**Comment by krzyk** [comment]
@mkordas @HDouss here it is (in .rultor.yml):
```
    mvn clean site-deploy -Pgh-pages -Pqulice-profile -Psite --errors --settings ../settings.xml || echo 'site-deploy failed'
```

It looks like github site plugin is buggy and almost not maintained (https://github.com/github/maven-plugins - one/two releases per year) so I assume this is a workaround for making the releases work.
We could try to disable this (`|| echo 'site-deploy failed'`) in this PR, hoping that I will be able to do a successful release.

**Comment by HDouss** [comment]
@krzyk I think this a different issue. After disabling it, should we reenable it, or will it be fine like this.

**Comment by krzyk** [comment]
@HDouss yes, it is a different issue

**Comment by HDouss** [comment]
@mkordas Do you have any comments for this PR ?

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by davvd** [comment]
> @davvd please assign @mkordas 

@krzyk OK @mkordas please go ahead, this task is yours

**Comment by HDouss** [comment]
@mkordas Do you have any comments for this PR ?

**Comment by mkordas** [comment]
@HDouss sorry for delay, now I'm on it officially

**Comment by mkordas** [comment]
@HDouss just remove `|| echo 'site-deploy failed'` from Rultor and I think we are done here

**Comment by HDouss** [comment]
@mkordas Thanks. According to @krzyk, it should be adressed on another issue (if any).
>@HDouss yes, it is a different issue

**Comment by mkordas** [comment]
@HDouss you are right, looks good to merge

**Comment by mkordas** [comment]
@rultor merge please

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by mkordas** [comment]
@rultor deploy

**Comment by krzyk** [comment]
@rultor deploy

**Comment by davvd** [comment]
@rultor deploy now pls

**Comment by mkordas** [comment]
@yegor256 can I get payment here?

**Comment by yegor256** [comment]
@davvd pls add extra 15 mins to @mkordas

**Comment by davvd** [comment]
> @davvd pls add extra 15 mins to @mkordas 

@yegor256 I've paid 15 mins to @mkordas in transaction `56b2f9a30f8b3202ec00003e`

**Comment by davvd** [comment]
@mkordas 10 mins added to @krzyk account (our architect), payment ID is `76497847`, since quality is good here

**Comment by mkordas** [comment]
@yegor256 I should have 9 mins more here

**Comment by mkordas** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@davvd pls add extra 9 mins to @mkordas

**Comment by davvd** [comment]
> @davvd pls add extra 9 mins to @mkordas 

@yegor256 9 mins extra was just paid to @mkordas, transaction `56d420379f490443ad000293`

**Pull request merged**
