### PR TITLE
#582 using qulice 0.15.1

### PR DESCRIPTION
**Pull request by krzyk**
#582 
* updated to use qulice 0.15.1

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@dmzaytsev this pull request is for you,please review

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by davvd** [comment]
@dmzaytsev Thanks for your contribution, **16 mins** was added to your account, payment ID is `74517996`, 1 hour and 46 mins spent total. review comments (c=1) added as a bonus. +16 added to your rating, at the moment it is: [+1723](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
