### PR TITLE
Fix small typo in Markdown link

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by davvd** [comment]
@valery1707 Thanks, let me find someone who can review this pull request

**Comment by davvd** [comment]
@krzyk the PR is rather short, please review it

**Comment by valery1707** [comment]
@davvd , @krzyk any news?

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request merged**
