### PR TITLE
#856 Checkstyle minor upgrade to improve performance

### PR DESCRIPTION
**Pull request by longtimeago**
#856 Checkstyle minor upgrade to improve performance

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#857` is in scope.

**Comment by krzyk** [comment]
@rultor merge

**Comment by longtimeago** [comment]
@krzyk thanks!
And release, please ;)

**Comment by krzyk** [comment]
@longtimeago there are test failures in build https://github.com/teamed/qulice/issues/798, strange

**Pull request merged**
