### PR TITLE
#411 Allow proper indentation in complex annotations

### PR DESCRIPTION
**Pull request by mkordas**
For #411:
* Update Checkstyle to 6.15
* Add test confirming that indentation works correctly now

### CODE REVIEW

**Comment by davvd** [comment]
@mkordas Thanks, let me find someone who can review this pull request

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk right, I removed "postponed" tag

**Comment by davvd** [comment]
@dmzaytsev it's yours,please review

**Comment by dmzaytsev** [comment]
@mkordas please add one more test case to be sure Qulice reports about incorrect  indentations as the ticket reporter mentioned
```
@SuppressWarnings(
    {
        "PMD.TooManyMethods",
        "PMD.ExcessiveImports",
        "PMD.AvoidDuplicateLiterals"
    }
    )
public final class Test {}
```

**Comment by mkordas** [comment]
@dmzaytsev but such test case doesn't fail. Indentation check just calculates minimal indentation, it doesn't complain on bigger one. Checkstyle doesn't have proper strict indentation feature yet, maybe someday...

**Comment by dmzaytsev** [comment]
@mkordas 

> longtimeago commented on 3 Mar 2015
> This code should fail the check (now it pass):

this bug has been accepted by the architect, that's why I have asked about a new test

@krzyk what do you think?

**Comment by krzyk** [comment]
@dmzaytsev it's a constant problem with checkstyles indentation check, @mkordas so I think for now we will need a todo, maybe will look at this in the future.

**Comment by mkordas** [comment]
@dmzaytsev @krzyk please see b9b662b9ee786bea692f0be9c70e166cfb9da22e

**Comment by mkordas** [comment]
@dmzaytsev @krzyk please see a4af148e990874767bd082ebce7d4e3fa29be5b8

**Comment by dmzaytsev** [comment]
@mkordas thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@dmzaytsev 10 mins added to @krzyk account (our architect), payment ID is `77111109`, since quality is good here; Much obliged! I have added **19 mins** to your account in payment "77111126", 24 hours and 36 mins spent; you're getting extra minutes here (c=4); +19 added to your rating, current score is: [+3073](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
