### PR TITLE
For #950: Tests for UseStringIsEmptyRule

### PR DESCRIPTION
**Pull request by paulodamaso**
For #950:
- Added tests for `UseStringIsEmptyRule` when the tested string is accessed using `this.` or by a method
- Left puzzle for fixing the implementation
- Left puzzle for completing the tests with all the conditions

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#978](https://github.com/teamed/qulice/issues/978) is now in scope, role is `REV`

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#978](https://github.com/teamed/qulice/issues/978); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@paulodamaso when #979 is merged to master, sync with master and we will try again

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#978](https://github.com/teamed/qulice/issues/978); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#978](https://github.com/teamed/qulice/issues/978); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#978](https://github.com/teamed/qulice/issues/978); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#978` is not assigned, can't get performer

**Pull request merged**
