### PR TITLE
#746 refactored logging of pmd check

### PR DESCRIPTION
**Pull request by krzyk**
#746 
* pmd check logging refactored (it now uses `ResourceValidator`)
* fixed maven and ant plugins and tests

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks, let me find someone who can review this pull request

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent 

@krzyk right, I added "urgent" label

**Comment by krzyk** [comment]
@davvd this is not urgent

**Comment by davvd** [comment]
> @davvd this is not urgent 

@krzyk sure, thanks, I removed "urgent" tag to it

**Pull request closed without merging**
