### PR TITLE
#462 upgraded to latest PMD

### PR DESCRIPTION
**Pull request by krzyk**
#462 
* upgrade to PMD 5.3.4

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@yegor256 pull request is rather short, review it please

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor merge again

**Comment by davvd** [comment]
@yegor256 **17 mins** sent to your balance (ID `000-8414ecc5`), many thanks! It took 115 hours and 49 mins.

review comments (c=2) added as a bonus

+17 added to your rating, current score is: [+13713](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Comment by krzyk** [comment]
@rultor deploy pls

**Comment by yegor256** [comment]
@rultor deploy

**Pull request merged**
