### PR TITLE
#706 disabled bogus exception check

### PR DESCRIPTION
**Pull request by krzyk**
#706 
* temporarily disabled bogus exception check
* added todo to enable it after jcabi/jcabi-maven-plugin#48 is fixed

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Let me find a reviewer for this pull request, thanks for submitting it

**Comment by longtimeago** [comment]
@krzyk finally, we will have it! :+1:

**Comment by krzyk** [comment]
@longtimeago almost, unfortunately fixes in jcabi-maven-plugin are quite slow, so first I'll disable it

**Comment by krzyk** [comment]
@davvd please find a reviewer

**Comment by davvd** [comment]
> @davvd please find a reviewer

@krzyk OK

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed 

@krzyk OK, I un-labeled it as "postponed" tag

**Comment by krzyk** [comment]
@davvd any chance for a reviewer?

**Comment by krzyk** [comment]
@davvd please assign @longtimeago

**Comment by davvd** [comment]
> @davvd please assign @longtimeago 

@krzyk too many tasks (3) are active in the project already, can't assign new ones

**Pull request closed without merging**
