### PR TITLE
#420 added handling of constants in inner classes

### PR DESCRIPTION
**Pull request by krzyk**
#420 
* recreated problem in test (`Valid.java`)
* fixed by checking inner class definition for private constants

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks for the pull request, let me find a reviewer..

**Comment by davvd** [comment]
@carlosmiranda please review,thanks

**Comment by carlosmiranda** [comment]
@rultor looks good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@carlosmiranda Much obliged! I have added **16 mins** to your account in payment "66850928", 26 hours and 39 mins spent. extra minutes for review comments (c=1). added +16 to your rating, now it is equal to [+3603](http://www.netbout.com/b/35023?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
