### PR TITLE
Allowing variables with minimum 2 characters

### PR DESCRIPTION
**Pull request by jrdalpra**
Solving issue #593

How I solved it

allowing 'id' or 3 to 12 characters at final, non final local variables and member names.
allowing 'id' or at leat 3 characters at method parameters names
refactoring test to match new restrictions.
ignoring 'FinalLocalVariable' check when testing the variables names (we don't need to test it here)

### CODE REVIEW

**Comment by mkordas** [comment]
@jrdalpra please close this one and continue with #615. I need to finish my code review there.

**Comment by jrdalpra** [comment]
@mkordas I deleted the fork, created another one and made my changes again. I'm afraid we can't continue with the other PR. :(

**Comment by mkordas** [comment]
@krzyk what should be done in such cases?

**Comment by krzyk** [comment]
@mkordas what's the problem? I don't really understand what @jrdalpra said :)
Do you have 2 PRs or one?

**Comment by krzyk** [comment]
@mkordas rule is that we should have one PR, but from time to time we have more than one PR per issue

**Comment by mkordas** [comment]
@krzyk but will I be paid for #615 review? Who will review this one? Who will check that comments from first review are incorporated?

**Comment by jrdalpra** [comment]
my bad. There are two PR. The first one was too messy, so I decided to start all over again. Deleted the first fork, created a new one and made my changes again. That`s the history. There's any way to correct my mistake?

**Comment by krzyk** [comment]
@mkordas I can assign you to the second one also
@jrdalpra nope, I don't know I usually remove the PR and create a clean one

**Comment by krzyk** [comment]
@mkordas as for the payment, you should get it, but maybe you will have to ping Yegor about it

**Comment by krzyk** [comment]
@davvd assign @mkordas

**Comment by mkordas** [comment]
@krzyk thanks for help and assignment

**Comment by mkordas** [comment]
@jrdalpra for consistency we should also allow `id` method parameter names, what do you think?

**Comment by mkordas** [comment]
@jrdalpra ping

**Comment by jrdalpra** [comment]
@mkordas <https://github.com/mkordas> I'll do ASAP

On Sunday, January 17, 2016, Michal Kordas <notifications@github.com> wrote:

> @jrdalpra <https://github.com/jrdalpra> ping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/teamed/qulice/pull/621#issuecomment-172381358>.
>


-- 
José Volmei Dal Prá Junior - (49) 9112 9359
Bacharel em Ciência da Computação - UnoChapecó
Pós-Graduado em Desenvolvimento de Software Com Java - Unoesc Xxe
Consultor Java e TotalCross
https://github.com/jrdalpra
http://www.kombo.com.br/meucurriculo/jrdalpra
http://www.linkedin.com/in/jrdalpra
msn: jr_dalpra@hotmail.com
skype: jrdalpra
e-mail: jrdalpra@gmail.com

**Comment by davvd** [comment]
@jrdalpra Many thanks for the PR, let me find a reviewer for it

**Comment by davvd** [comment]
@carlosmiranda it's yours,please review

**Comment by mkordas** [comment]
@krzyk please try assigning me again here

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by krzyk** [comment]
@carlosmiranda sorry, we just need to continue previous review here

**Comment by mkordas** [comment]
@jrdalpra for consistency we should also allow id method parameter names, what do you think?

**Comment by jrdalpra** [comment]
@mkordas doing

**Comment by mkordas** [comment]
@jrdalpra OK, I will review in about 7 hours

**Comment by jrdalpra** [comment]
@mkordas I'm almost finishing. 30 min max.

**Comment by jrdalpra** [comment]
@mkordas done

**Comment by mkordas** [comment]
@jrdalpra looks good, thank you!

**Comment by mkordas** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
> @davvd assign @mkordas

@krzyk of course! @mkordas it's your ticket now, please go ahead

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk done, @mkordas is assigned to this task, and is already working on it, AFAIK

**Comment by mkordas** [comment]
@rultor deploy

**Comment by davvd** [comment]
@rultor deploy now pls

**Comment by davvd** [comment]
@mkordas since quality is good, 10 mins paid to @krzyk (our architect), transaction `76561459`

**Pull request merged**
