### PR TITLE
#648 upgrade to qulice 0.15.4

### PR DESCRIPTION
**Pull request by krzyk**
#648
* added since tags to classes, fixed non-static access for two variables

Since tags are not using  patch version, only the first two. Those make more sense as it is not always known ahead of time which version will be released next, patch one or minor one.

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@carlosmiranda please review, thanks

**Comment by carlosmiranda** [comment]
@rultor good to merge

**Comment by davvd** [comment]
@rultor deploy pls

**Comment by davvd** [comment]
@carlosmiranda Thanks a lot, I just topped your account for **16 mins**, transaction ID `76561474`, total time was 2 hours and 18 mins. you're getting extra minutes here (c=1). +16 added to your rating, at the moment it is: [+2774](http://www.netbout.com/b/35023?open=rating)

**Pull request merged**
