### PR TITLE
#485 Estimate project size

### PR DESCRIPTION
**Pull request by mkordas**
For #485:
* project size estimated using Scope Champions method

### CODE REVIEW

**Comment by davvd** [comment]
@mkordas Many thanks for the PR, let me find a reviewer for it

**Comment by davvd** [comment]
@pinaf review this one, please

**Comment by pinaf** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@pinaf I just added **16 mins** to your account, many thanks for your contribution (AP-1DU59544HT5906218).. 93 hours and 35 mins spent here. extra minutes for review comments (c=1). +16 added to your rating, current score is: [+5106](http://www.netbout.com/b/35128?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
