### PR TITLE
Fixed a typo in pmd/ruleset.xml

### PR DESCRIPTION
**Pull request by jiakuan**

### CODE REVIEW

**Comment by davvd** [comment]
@jiakuan Thanks for the pull request, let me find a reviewer..

**Comment by davvd** [comment]
@krzyk review this pull request please, it is rather short for a full review

**Comment by krzyk** [comment]
@jiakuan The build fails, that text was used also in unit tests.

**Comment by jiakuan** [comment]
Oh, that's interesting. Let me check and fix it.

**Comment by krzyk** [comment]
@jiakuan Cool, looks good now

**Comment by krzyk** [comment]
@rulto merge pls

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@rultor deploy

**Comment by davvd** [comment]
@krzyk I added **20 mins** to your account, many thanks for working with the project (92485330)! The completion time here was 457 hours.

you're getting extra minutes here (c=5)

+20 to your rating, your total score is [+1324](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
