### PR TITLE
For #1017: Update jcabi-parent version.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1017: Update jcabi-parent version.
- Updated `jcabi-parent` to version `0.49.3`
- Added `xcop` installation to rultor and travis.

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @krzyk[/z](https://www.0crat.com/u/krzyk) please review this and merge or reject

**Comment by krzyk** [comment]
@paulodamaso you'll need to fix formatting of e ery xml file, że see xcop output in travis. Mostly it should be just indentation change from 4 spaces to 2.

**Comment by paulodamaso** [comment]
@krzyk Something is wrong, xcop is complaining about the license text in xml files now, but if I change it it'll break all other files

**Comment by krzyk** [comment]
@paulodamaso strange, but xcop works in other projects, so maybe there is something else wrong here?

**Comment by paulodamaso** [comment]
@krzyk Sorry I don't get time to work on this anymore

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#1029` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
