### PR TITLE
#905 removed cobertura

### PR DESCRIPTION
**Pull request by krzyk**
#905 
Got rid of cobertura.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#911](https://github.com/teamed/qulice/issues/911) is now in scope, role is `REV`

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#911](https://github.com/teamed/qulice/issues/911); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#911` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#911](https://github.com/teamed/qulice/issues/911) is now out of scope

**Pull request merged**
