### PR TITLE
allow custom checkstyle check.xml

### PR DESCRIPTION
**Pull request by androidfred**
Issue: https://github.com/teamed/qulice/issues/507

Qulice master won't build for me, and neither will this branch, so I unfortunately can't verify that it works.

### CODE REVIEW

**Comment by krzyk** [comment]
@androidfred please see https://github.com/teamed/qulice/issues/326#issuecomment-58991903

**Comment by davvd** [comment]
@androidfred Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@carlosmiranda review this one,please

**Comment by carlosmiranda** [comment]
@androidfred Thanks for the PR, but we can't accept this, for the reasons stated in the original ticket. If you need a custom Checkstyle rule you can manually configure it in your `pom.xml`. This is the case for most of the tools that Qulice uses.

**Comment by krzyk** [comment]
@davvd this is invalid

**Comment by davvd** [comment]
> @davvd this is invalid

@krzyk got it, "invalid" label here

**Comment by krzyk** [comment]
@androidfred please close this PR

**Comment by androidfred** [comment]
Closing

**Pull request closed without merging**
