### PR TITLE
added dependency to cater to jdk9

### PR DESCRIPTION
**Pull request by ashtonhogan**
as per https://github.com/teamed/qulice/issues/871

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#872](https://github.com/teamed/qulice/issues/872) is now in scope, role is `REV`

**Comment by ashtonhogan** [comment]
bump

**Comment by 0crat** [comment]
The job [#872](https://github.com/teamed/qulice/issues/872) is now out of scope

**Pull request closed without merging**
