### PR TITLE
#412 added handling of nicks in author tag

### PR DESCRIPTION
**Pull request by krzyk**
#412 
* recreated problem in unit test
* changed number of words required in the author name to 1

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks, I will find someone to review this PR soon

**Comment by davvd** [comment]
@yegor256 this pull request is for you,please review

**Comment by krzyk** [comment]
@yegor256 I've updated the code (now it works correctly on travis)

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by krzyk** [comment]
@yegor256 please try again, there was a problem with connection to maven central

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@yegor256 thank you, added **17 mins** to your acc, payment num is `000-7ba277f5`, 195 hours and 45 mins spent in total to complete

review comments (c=2) added as a bonus

+17 added to your rating, at the moment it is: [+9392](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
