### PR TITLE
#454 upgraded PMD to handle method references

### PR DESCRIPTION
**Pull request by krzyk**
#454 
* PMD upgraded to 5.3.3
* added test to check handling of method references

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@pinaf review this one, please

**Comment by pinaf** [comment]
@krzyk I suppose breaking down the pmd dependencies ensures we no longer need the exclusions for `junit` and `xml-apis`, correct?

**Comment by krzyk** [comment]
@pinaf actually I don't know, I tried with them removed and the build works, so I assume this was a stale exclusion since pre-5 days.

**Comment by pinaf** [comment]
@krzyk alright, thank you.

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@pinaf Many thanks! **18 mins** were added to your account in Transaction ID `AP-5D925530J7155444S` (task took 65 hours and 56 mins). review comments (c=3) added as a bonus. added +18 to your rating, now it is equal to [+4830](http://www.netbout.com/b/35128?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
