### PR TITLE
#366  qulice-maven-plugin:0.12 removed from pom.xml, parent updated to 0.32

### PR DESCRIPTION
**Pull request by alevohin**
Issue #366 resolved.
qulice-maven-plugin:0.12 removed from pom.xml
parent updated to 0.32

### CODE REVIEW

**Comment by davvd** [comment]
Thanks, I'll find someone to review this PR soon

**Comment by davvd** [comment]
@carlosmiranda this pull request is for you, please review

**Comment by carlosmiranda** [comment]
@alevohin Thanks for the pull request! I don't have any comments

**Comment by carlosmiranda** [comment]
@rultor Let's merge please.

**Comment by alevohin** [comment]
@yegor256 could you confirm merge?

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@carlosmiranda thanks, I just added **16 mins** to your account, payment `50344442`

+16 added to your rating, at the moment it is: [+1351](http://www.netbout.com/b/35023?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
