### PR TITLE
#767 Qulice release 0.16.4 is too slow

### PR DESCRIPTION
**Pull request by dskalenko**

### CODE REVIEW

**Comment by davvd** [comment]
@dskalenko I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@mkordas it's yours, please review

**Comment by mkordas** [comment]
@dskalenko I'll do a review today

**Comment by mkordas** [comment]
@dskalenko thanks, looks good!
@krzyk please check again

**Comment by mkordas** [comment]
@rultor merge

**Comment by krzyk** [comment]
@dskalenko looks good, thanks

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@dskalenko actually, you should add a description in the PR

**Comment by mkordas** [comment]
@dskalenko also do not forget to link to issue in description

**Comment by dskalenko** [comment]
@krzyk 
@mkordas 
Done :)

**Comment by krzyk** [comment]
@dskalenko and now you have to ask issue creator to close it, and we are done :)

**Comment by mkordas** [comment]
@dskalenko usually we put bit more description about how issue was solved and why in that way, but there are no strict rules, so for me it is also fine :)

**Comment by davvd** [comment]
@mkordas quality is good here, 10 mins added to @krzyk (our architect) in transaction 89369916; paid, thanks, added **20 mins** to your account, payment `575934c9c59ef86707000001`, 115 hours and 3 mins was spent; extra minutes for review comments (c=5); +20 to your rating, your total score is [+5442](http://www.netbout.com/b/36080?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
