### PR TITLE
#491 fixed false error when during static field initialization

### PR DESCRIPTION
**Pull request by krzyk**
#491 
* recreated problem in unit test
* fixed PMD rule to ignore static fields

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Let me find a reviewer for this pull request, thanks for submitting it

**Comment by davvd** [comment]
@pinaf this pull request is for you, please review

**Comment by pinaf** [comment]
@rultor merge

**Comment by davvd** [comment]
@pinaf **16 mins** added to your account (payment number `AP-91F80662T9783320C`), many thanks for your contribution! 22 hours spent here.... you're getting extra minutes here (c=1)... +16 to your rating, your total score is [+4178](http://www.netbout.com/b/35128?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
