### PR TITLE
#441 exclude files created in temp directory

### PR DESCRIPTION
**Pull request by krzyk**
#441 
* recreated problem in integration test
* fixed by moving created exclude files into temporary folder

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@krzyk no need to do code review here, it's a small pull request from the architect

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@rultor deploy

**Pull request merged**
