### PR TITLE
#335 Migration to Checkstyle 5.9 to support Java 8 syntax

### PR DESCRIPTION
**Pull request by palyuga**

### CODE REVIEW

**Comment by davvd** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@longtimeago this pull request is for you, please review

**Comment by longtimeago** [comment]
@palyuga Have you tried to run ```mvn clean install -Pqulice``` ?

**Comment by palyuga** [comment]
@longtimeago yes, built fine for me, but I see the problem in Travis logs: looks like findbugs 5.9 is compiled with jdk7 and now build fails on openjdk 6. 
Should we support building with openjdk 6?

**Comment by longtimeago** [comment]
@palyuga Here http://www.qulice.com/qulice-maven-plugin/plugin-info.html mentioned that qulice should support java 1.6, but I'm not really sure we should stick with that.
@yegor256 What do you think?

**Comment by yegor256** [comment]
@longtimeago let's remove that requirement and make 1.7 the smallest version

**Comment by longtimeago** [comment]
@should it be done in current PR?

**Comment by yegor256** [comment]
@longtimeago just fix the `.travis.yml` in the branch

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@longtimeago Many thanks! **18 mins** were added to your account in Transaction ID `50596434`... added +18 to your rating, now it is equal to [+1277](http://www.netbout.com/b/35024?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
