### PR TITLE
#424 added excludes to jslint

### PR DESCRIPTION
**Pull request by krzyk**
#424 
* added handling of excludes in jslint (it uses ant style pattern internally)
* added documentation for the non-standard exclude pattern (similar to codenarc)

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks, let me find someone who can review this pull request

**Comment by davvd** [comment]
@pinaf it's yours, please review

**Comment by pinaf** [comment]
@rultor merge

**Comment by davvd** [comment]
@pinaf Thanks a lot, I just topped your account for **16 mins**, transaction ID `AP-39J15194AX2316545`, total time was 19 hours and 13 mins

review comments (c=1) added as a bonus

added +16 to your rating, now it is equal to [+4162](http://www.netbout.com/b/35128?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
