### PR TITLE
#951 fixing suppresions

### PR DESCRIPTION
**Pull request by krzyk**
#951 
* correcting suppression filters path to use classpath

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @krzyk[/z](https://www.0crat.com/u/krzyk) please review this and merge or reject

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#955` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
