### PR TITLE
For #1037:Upgrade ChecksTest from qulice-checkstyle to Junit5.

### PR DESCRIPTION
**Pull request by zCRUSADERz**
For #1037 
- Upgrade [ChecksTest](https://github.com/teamed/qulice/blob/master/qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java) from Junit4 to Junit5.
- Now [ChecksTest](https://github.com/teamed/qulice/blob/master/qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java) from qulice-pmd runs automatically when building by maven.

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#1041](https://github.com/teamed/qulice/issues/1041) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#1041](https://github.com/teamed/qulice/issues/1041); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@zCRUSADERz this is not for #939 but for #1030, please update the description and update the puzzle in the qulice-maven-plugin/pom.xml (the text there should say that the rest of the project should be upgraded, not only qulice-maven-plugin)

**Comment by zCRUSADERz** [comment]
@krzyk i was wrong, these changes do not apply to these puzzles #939 and #1030. [ChecksTest](https://github.com/teamed/qulice/blob/master/qulice-checkstyle/src/test/java/com/qulice/checkstyle/ChecksTest.java) from qulice-checkstyle, this test forgot upgrade to Junit5. Therefore, he fell out of the assembly by maven.

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#1041` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1041](https://github.com/teamed/qulice/issues/1041) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Pull request merged**
