### PR TITLE
For #847: Enforce parameter order in javadoc

### PR DESCRIPTION
**Pull request by paulodamaso**
For #847: Enforce parameter order in javadoc
- Added test for parameter order check
- Left puzzle to complete check implementation

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#986](https://github.com/teamed/qulice/issues/986) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#986](https://github.com/teamed/qulice/issues/986); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@krzyk ping

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#986](https://github.com/teamed/qulice/issues/986); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge

**Comment by krzyk** [comment]
@paulodamaso please merge changes from master and update the copyright years

**Comment by paulodamaso** [comment]
@krzyk Done, please take a look.

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#986` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#986](https://github.com/teamed/qulice/issues/986) is now out of scope

**Pull request merged**
