### PR TITLE
#489 fix NPE in BracketsStructure check

### PR DESCRIPTION
**Pull request by mkordas**
#489
* reproduce problem in unit test
* fix NPE by checking if list of expressions contains any element

### CODE REVIEW

**Comment by davvd** [comment]
@mkordas Thanks, I will find someone to review this PR soon

**Comment by davvd** [comment]
@krzyk the pull request is rather small, pls review it

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@rultor deploy pls

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk sure, thanks, I removed "postponed" tag to it

**Comment by davvd** [comment]
@krzyk Thanks so much! Your account was topped up for **18 mins** (transaction ID is `70054413`, the task took 23 hours and 11 mins)... you're getting extra minutes here (c=3)... +18 to your rating, your total score is [+2726](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
