### PR TITLE
#966 temporarly disable xcop

### PR DESCRIPTION
**Pull request by krzyk**
#966 
* disable xcop for now (so we can upgrade it later)

### CODE REVIEW

**Comment by krzyk** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor stop

**Comment by krzyk** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#1002` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
