### PR TITLE
#909 logging file being processed

### PR DESCRIPTION
**Pull request by krzyk**
#909 
Added logging of currently processed file in PMD.

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @krzyk[/z](https://www.0crat.com/u/krzyk) please review this and merge or reject

**Comment by krzyk** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor release `0.17.4`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#910` is not assigned, can't get performer

**Pull request merged**
