### PR TITLE
Leftovers after removal of RedundantThrows check from Checkstyle #524

### PR DESCRIPTION
**Pull request by jrdalpra**
Solving https://github.com/teamed/qulice/issues/524

Just removed references and test cases

### CODE REVIEW

**Comment by davvd** [comment]
@jrdalpra Many thanks for the PR, let me find a reviewer for it

**Comment by davvd** [comment]
@dmzaytsev please review, thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@dmzaytsev thanks, paid, **16 mins** to your account, payment ID is `73494657`, task took 2 hours and 57 mins to complete; extra minutes for review comments (c=1); +16 to your rating, your total score is [+1292](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
