### PR TITLE
#800 usign qulice 0.17.4

### PR DESCRIPTION
**Pull request by krzyk**
#800 
* upgraded qulice plugin to 0.17.4
* fixed resulting errors

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#914](https://github.com/teamed/qulice/issues/914) is now in scope, role is `REV`

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#914](https://github.com/teamed/qulice/issues/914); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#914` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#914](https://github.com/teamed/qulice/issues/914) is now out of scope

**Pull request merged**
