### PR TITLE
#280 jcabi-xml version upgrade for connection retry functionality

### PR DESCRIPTION
**Pull request by carlosmiranda**

### CODE REVIEW

**Comment by davvd** [comment]
Many thanks, I'll find someone to review it before we merge

**Comment by davvd** [comment]
@krzyk this pull request is for you, please review

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@krzyk I just added **16 mins** to your account, many thanks for your contribution... +16 to your rating, your total score is [+2210](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
