### PR TITLE
#252 XmlValidator: Fix all test cases to pass with formating check enabl...

### PR DESCRIPTION
**Pull request by nhekfqn**
#252 XmlValidator: Fix all test cases to pass with formating check enabled and change default value to true.

### CODE REVIEW

**Comment by nhekfqn** [comment]
ci build failed because qulice-findbugs has compilation warnings on openjdk6

**Comment by davvd** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@carlosmiranda it's yours,please review

**Comment by nhekfqn** [comment]
@carlosmiranda It should be quick one, could you please take a look? I have a day to finish this, so your help to close it today will be appreciated.

**Comment by carlosmiranda** [comment]
@nhekfqn Looks good, thanks!

**Comment by carlosmiranda** [comment]
@rultor Let's merge!

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by nhekfqn** [comment]
@carlosmiranda Thanks!

**Comment by davvd** [comment]
@carlosmiranda Thanks so much! Your account was topped up for **17 mins** (transaction ID is `50303113`). +17 added to your rating, current score is: [+1121](http://www.netbout.com/b/35023?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
