### PR TITLE
Fix StringLiteralsConcatenationCheck

### PR DESCRIPTION
**Pull request by Happy-Neko**
Fix for #502. 
Add recursive string literal search.

### CODE REVIEW

**Comment by Happy-Neko** [comment]
@davvd Please proceed with code review.

**Comment by davvd** [comment]
@happy-neko Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@dmzaytsev please review, thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor merge pl

**Comment by dmzaytsev** [comment]
@davvd assign QR review please

**Comment by krzyk** [comment]
@dmzaytsev there is no QA here :)

**Comment by krzyk** [comment]
@rultor deploy

**Comment by davvd** [comment]
@dmzaytsev Many thanks! **17 mins** were added to your account in Transaction ID `76497878` (task took 5 hours and 4 mins)... extra minutes for review comments (c=2)... added +17 to your rating, now it is equal to [+2949](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
