### PR TITLE
#396 Add information about proxy usage to documentation

### PR DESCRIPTION
**Pull request by mkordas**
For #396:
* add summary from discussion in #393 to FAQ and README

### CODE REVIEW

**Comment by davvd** [comment]
@mkordas Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by davvd** [comment]
@krzyk pull request is rather short, review it please

**Comment by krzyk** [comment]
@mkordas I would also add this information in README.md, and also mention that addind proxy to `mvn` command line is possible

**Comment by mkordas** [comment]
@krzyk info added to README, please check

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by mkordas** [comment]
@rultor deploy

**Comment by davvd** [comment]
@rultor deploy now pls

**Comment by davvd** [comment]
@krzyk thanks, I just added **17 mins** to your account, payment `74718538`, 19 hours and 53 mins spent; review comments (c=2) added as a bonus; +17 added to your rating, current score is: [+3564](http://www.netbout.com/b/35035?open=rating)

**Pull request merged**
