### PR TITLE
#472 enforce documentation of parameters

### PR DESCRIPTION
**Pull request by krzyk**
#472 
* added test to recreate the problem
* enabled JavadocType check to force documentation of class parameters

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@dmzaytsev review this one, please

**Comment by dmzaytsev** [comment]
@krzyk looks good, thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@rultor please deploy

**Comment by davvd** [comment]
@dmzaytsev done, I added **17 mins** in payment `67442879`, 48 hours and 9 mins spent to complete this. you're getting extra minutes here (c=2). +17 added to your rating, current score is: [+1422](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
