### PR TITLE
Invalidate methods that throw from a catch that could otherwise be static

### PR DESCRIPTION
**Pull request by gumbelmj**
#623 Updated code and tests to find methods that should static if they catch and re-throw an exception.

### CODE REVIEW

**Comment by davvd** [comment]
@gumbelmj Let me find a reviewer for this pull request, thanks for submitting it

**Comment by davvd** [comment]
@krzyk pull request is rather short, review it please

**Comment by krzyk** [comment]
@gumbelmj The idea here is to allow methods that have only `throw` in the body (and nothing else except the exception class), your current solution probably will allow if/while and all other java constructs.

**Comment by krzyk** [comment]
@gumbelmj throws can span multiple lines (2-3 are common), maybe it would be better to check that the method contains only one `;` and no `{`

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@krzyk I added **18 mins** to your account, many thanks for working with the project (77096920)! The completion time here was 119 hours and 55 mins.. extra minutes for review comments (c=3). +18 added to your rating, current score is: [+5569](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
