### PR TITLE
#331 - Custom message for qulice check License

### PR DESCRIPTION
**Pull request by AlexDag**
please, review job of #331

### CODE REVIEW

**Comment by davvd** [comment]
Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@krzyk it's yours, please review

**Comment by krzyk** [comment]
@AlexDag I think it won't work as expected, it will show that LICENSE is not found even if it is found, but has different content. Please add a test, to show that it is working as expected (I think the easiest is to add it to integration tests in `qulice-mave-plugin/src/it/checkstyle-*`

**Comment by AlexDag** [comment]
@krzyk  - here is the acceptance of this message was taken by @yegor256. About test unit - there not  need any additional unit test as the tests existen show this customized qulice message.

**Comment by krzyk** [comment]
@AlexDag I don't mean the text itself, but I think it will show not only when the file is missing but also when the text is slightly wrong.
Also, which test is checking for missing LICENSE.txt file?

**Comment by krzyk** [comment]
@AlexDag How is the update going?

**Comment by krzyk** [comment]
@AlexDag please close this PR if you are not longer working on it, thanks

**Comment by krzyk** [comment]
@AlexDag ping

**Comment by krzyk** [comment]
@AlexDag and ping again

**Comment by krzyk** [comment]
@yegor256 could you invalidate this PR? I don't think it will be finished.

**Comment by yegor256** [comment]
@krzyk right, I'm closing it

**Pull request closed without merging**
