### PR TITLE
#901 allow protected methods if they have override annotation

### PR DESCRIPTION
**Pull request by krzyk**
#901 
* protected methods are now allowed if they are inherited (and have `@Override` annotation)
* updated test

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#915](https://github.com/teamed/qulice/issues/915) is now in scope, role is `REV`

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `REV` is banned at [#915](https://github.com/teamed/qulice/issues/915); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#915` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#915](https://github.com/teamed/qulice/issues/915) is now out of scope

**Pull request merged**
