### PR TITLE
#908 removed AvoidInstantiatingObjectsInLoops

### PR DESCRIPTION
**Pull request by krzyk**
#908 
* removed PMD rule AvoidInstantiatingObjectsInLoops

### CODE REVIEW

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @krzyk[/z](https://www.0crat.com/u/krzyk) please review this and merge or reject

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#923` is not assigned, can't get performer

**Pull request merged**
