### PR TITLE
#447 added handling of constants in annotations

### PR DESCRIPTION
**Pull request by krzyk**
#447 
* recreated problem in unit test
* fixed handling of constants in method annotations
* added todo to fix problem in class and field annotations

### CODE REVIEW

**Comment by davvd** [comment]
@krzyk Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@yegor256 please review, thanks

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@rultor deploy pls

**Comment by davvd** [comment]
@yegor256 thanks, I just added **16 mins** to your account, payment `000-697f08ae`, 23 hours and 10 mins spent

review comments (c=1) added as a bonus

added +16 to your rating, now it is equal to [+12014](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
